# ==========================================
# Shygirl-Clash v1.0
# Author: 1Tjnco
# ==========================================

mixed-port: 7890
allow-lan: false
bind-address: "*"

mode: rule
log-level: info

ipv6: true

unified-delay: true
tcp-concurrent:  true
find-process-mode: strict

external-controller: 127.0.0.1:9090

profile:
  store-selected: true
  store-fake-ip: true
  
geodata-mode: true

geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb

sniffer:
  enable: false

  sniff:
    HTTP:
      ports:
        - 80
        - 8080-8880

    TLS:
      ports:
        - 443
        - 8443

dns:
  enable: true
  ipv6: false

  enhanced-mode: fake-ip

  fake-ip-range: 198.18.0.1/16

  default-nameserver:
    - 223.5.5.5

  nameserver:
    - https://dns.alidns.com/dns-query

  proxy-server-nameserver:
    - https://1.1.1.1/dns-query

  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query

  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

  - name: 🇹🇼 台湾家宽
    type: vless

    server: 151.242.188.152
    port: 443

    uuid: 7619026b-1410-4c9b-a35e-b0a36ba7db95

    network: tcp

    tls: true
    skip-cert-verify: false
    udp: true

    flow: xtls-rprx-vision
    
    servername: www.cloudflare.com

    client-fingerprint: chrome

    reality-opts:
      public-key: P8zntAEAj350fELTOlNe2UMZfakpn3YwdoPhuBLwVxI
      short-id: 9f3a7c2d5b1e8a90    
proxy-groups:

- name: 🚀 默认代理
  type: select
  proxies:
    - 🇹🇼 台湾家宽
    - DIRECT

  - name: 🤖 AI
    type: select
    proxies:
      - 🇹🇼 台湾家宽
      - DIRECT

  - name: 📱 Telegram
    type: select
    proxies:
      - 🇹🇼 台湾家宽
      - DIRECT

  - name: 🍎 Apple
    type: select
    proxies:
      - DIRECT
      - 🚀 默认代理

  - name: Ⓜ Microsoft
    type: select
    proxies:
      - DIRECT
      - 🚀 默认代理

  - name: 🎮 Game
    type: select
    proxies:
      - DIRECT
      - 🚀 默认代理

rule-providers:

  AI:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/AI.yaml
    path: ./ruleset/AI.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Apple.yaml
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Microsoft.yaml
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Telegram.yaml
    path: ./ruleset/Telegram.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Game.yaml
    path: ./ruleset/Game.yaml
    interval: 86400

  Proxy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Proxy.yaml
    path: ./ruleset/Proxy.yaml
    interval: 86400

  Direct:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/1Tjnco/Shygirl-clash/main/rules/Direct.yaml
    path: ./ruleset/Direct.yaml
    interval: 86400      
rules:

  - RULE-SET,AI,🤖 AI
  - RULE-SET,Telegram,📱 Telegram
  - RULE-SET,Apple,🍎 Apple
  - RULE-SET,Microsoft,Ⓜ Microsoft
  - RULE-SET,Game,🎮 Game
  - RULE-SET,Proxy,🚀 默认代理
  - RULE-SET,Direct,DIRECT

  - MATCH,🚀 默认代理
